### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by JanVeb** [paytonjewell/ReactPortfolioTemplate#5]
Hi there, really cool template, I'm playing already with it and thinking about using it for my first portfolio page.

Since there is no license, I wasn't sure, can I use it and under what terms?

Thank you

**Comment by paytonjewell** [comment]
Hi there, thank you so much I’m glad you like it! This template is totally free to use and change as you like — totally not required but i would just appreciate attribution somewhere, could leave it in the footer or remove the footer part and just put it in the code somewhere, it doesn’t matter :) i’d also love to see how it turns out if you end up using it!

**Comment by JanVeb** [comment]
Great, thank you.

I'm still in the process of creating it, here is what I have till now if you are interested, made some changes, let me know if you have any issues with it

https://janveb.github.io/

**Comment by paytonjewell** [comment]
This is so cool! I love the different animated backgrounds for light/dark mode!
