### ISSUE TITLE
error in npm install

### ISSUE THREAD

**Issue by Phyxioss** [paytonjewell/ReactPortfolioTemplate#8]
Hello. First of all, I apologize for my bad english. I am encountering many errors during npm install.

npm and node versions:

npm: '8.11.0',
node: '16.16.0',
Thanks in advance.

**Comment by paytonjewell** [comment]
Hello! I'm so sorry you're running into issues with installation. 

If you look [here](https://github.com/paytonjewell/ReactPortfolioTemplate/issues/6#issuecomment-1209183309), the project requires Node 14.x right now because of a dependency, node-sass. I plan to add this to the documentation, and to change to a different dependency later so that this issue won't happen. I'm sorry for the inconvenience! For now, if you switch to Node 14, you should be able to install successfully :)
